[workspace]
resolver = "3"
members = [
    "crates/protocol",
    "crates/cli",
]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
maestro-protocol = { path = "crates/protocol" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
too_many_lines = "warn"
cognitive_complexity = "warn"
